package domain;

public class Money {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.uid
     *
     * @mbg.generated Sun Oct 06 23:25:49 CST 2019
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column money.money
     *
     * @mbg.generated Sun Oct 06 23:25:49 CST 2019
     */
    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.uid
     *
     * @return the value of money.uid
     *
     * @mbg.generated Sun Oct 06 23:25:49 CST 2019
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.uid
     *
     * @param uid the value for money.uid
     *
     * @mbg.generated Sun Oct 06 23:25:49 CST 2019
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column money.money
     *
     * @return the value of money.money
     *
     * @mbg.generated Sun Oct 06 23:25:49 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column money.money
     *
     * @param money the value for money.money
     *
     * @mbg.generated Sun Oct 06 23:25:49 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }
}